const express = require("express")
const connectDB = require("./config/db")
const Match=require("./schemas/match")
const Stadium=require("./schemas/stadium")
const Seat=require("./schemas/seat")
const Reservation=require("./schemas/reservation")
const app = express()
connectDB()
app.listen(3000,()=>console.log("server running on port 3000"))